version: "3.8"

services:
  api:
    image: 953207960640.dkr.ecr.us-east-1.amazonaws.com/crewcall-api-production:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    ports:
      - 3000:3000

    environment:
      - NODE_ENV=production
      - PORT=${PORT} 
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - TYPEORM_SYNC=${TYPEORM_SYNC}
    volumes:
      - public_assets:/app/shared/public


  nginx:
    image: nginx:alpine
    platform: linux/amd64
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - public_assets:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  public_assets: